name = "greenfield-golf-club"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "greenfield-golf-club.pages.dev/*", custom_domain = true }
]

[[env.production.routes]]
pattern = "/*"
custom_domain = true
